name: res_client
description: A resgate.io client.
version: 0.8.6
homepage: https://github.com/farcaller/resclient-dart

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  web_socket_channel: ^2.4.4
  crypto: ^3.0.3
  json_annotation: ^4.8.1
  tuple: ^2.0.2
  html_template: ^0.3.0
  yaml_writer: ^2.0.0
  glog: ^1.3.0

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
