name: res_client
description: A resgate.io client.
version: 0.8.2
homepage: https://github.com/farcaller/resclient-dart

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  web_socket_channel: ^2.2.0
  crypto: ^3.0.2
  json_annotation: ^4.5.0
  tuple: ^2.0.0
  html_template: ^0.2.1
  yaml_writer: ^1.0.1
  glog: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
